server:
  protocol: http
  ip: localhost
  back_port: 3001
  front_port: 3000
models:
  Users:
    name_max_length: 50
    surname_max_length: 50
  Roles:
    name_max_length: 50
    description_max_length: 200